### ISSUE TITLE
Hex location to some stats

### ISSUE THREAD

**Issue by gregstein** [goto-bus-stop/recanalyst#60]
Hello,
I just want to ask you about locating recorded game info such as: Victorious Player, number of kills, and Civilization names.

I would appreciate it if you could tell me the Hex values or blocks that represent those.

Thank you,

**Comment by gregstein** [comment]
Hello,

Thank you so much Sir! I would appreciate it if you could check them because I have tried really hard but couldn't understand the positions assigned in your awesome library and I just need these info for Userpatch replays only.

Oh god if you could just tell me where is that achievement block in Hex, that would be a good start.  

About the separators in headeranalyser file:


$constant2 = pack('c*', 0x9A, 0x99, 0x99, 0x99, 0x99, 0x99, 0xF9, 0x3F) ==> This one only returns one block.

$separator = pack('c*', 0x9D, 0xFF, 0xFF, 0xFF) ==> This returns 4 blocks.

I think the other separators are not for Userpatch.

Thank you very much for all this unbelievable and professional work. Your coding skills are beyond professional as it took me hours to scan it LOL. And understand just a bit (At least managed to extract the stream, player names, and chat all thanks to you.

I will keep this pull open awaiting for your feedback.

Have a great rest of your day,
warm regards,

**Comment by goto-bus-stop** [comment]
I'm not a sir :)

If you just need UP support then it's fairly simple, compared to other game versions. The achievements block is stored similarly to chat so you are already halfway there. Chat message actions are in the recorded game body and start with 0x03FF or 0x04FF (`OP_META` or `OP_META2` followed by `META_CHAT` in [BodyAnalyzer.php][]). The achievements block is also stored as an action in the recorded game body and starts with 0x01FF (`OP_COMMAND` followed by `COMMAND_POSTGAME` in [BodyAnalyzer.php][]). recanalyst reads the achievements block here: https://github.com/goto-bus-stop/recanalyst/blob/master/src/Analyzers/PostgameDataAnalyzer.php

This is the achievements block using C struct syntax:
```cpp
struct ZoneData {
    char scenario_filename[32];
    int num_players;
    int duration;
    char allow_cheats;
    char complete; // not sure what this stands for
    char buf[10];
    float u0;
    char map_size;
    char map_id;
    char population; // * 25 for userpatch
    char u1;
    char victory_type; // 0 for conquest, etc
    char starting_age;
    char starting_resources;
    char all_techs_enabled;
    char reveal_map;
    char is_death_match;
    char is_regicide;
    char u2;
    char teams_locked;
    char speed_locked;
    char u3;

    struct PlayerData {
        char name[16];
        short total_score;
        short total_scores[8];
        char victory; // 1 if winner, 0 if not
        char civ_id;
        char color_id;
        char team;
        char num_allies;
        char u0; // always -1
        char is_mvp;
        char u1[3]; // padding
        char result; // don't remember what this is
        char u2[3]; // more padding

        struct MilitaryStats {
            short score;
            short units_killed;
            short hit_points_killed;
            short units_lost;
            short buildings_razed;
            short hit_points_razed;
            short buildings_lost;
            short units_converted;
            // amount of units killed / buildings razed against each player
            short player_units_killed[8];
            short player_buildings_razed[8];
        } military_score;

        struct EconomyStats {
            short score;
            short u0; // padding I think
            int food_collected;
            int wood_collected;
            int stone_collected;
            int gold_collected;
            short tribute_sent;
            short tribute_received;
            short trade_profit;
            short relic_gold;
            // tribute sent to each player
            short player_tribute_sent[8];
        } economy_score;

        short TechnologyStats {
            short score;
            short u0; // padding
            int feudal_time;
            int castle_time;
            int imperial_time; // all inseconds
            char map_exploration_percent;
            char research_count;
            char research_percent;
        } technology_stats;

        char u3; // padding

        struct SocietyStats {
            short score;
            char total_wonders;
            char total_castles;
            char relics_captured;
            char u0;
            short villager_high;
        } society_score;

        char u4[84]; // padding
    } players[8];
}
```

It sounds like it includes everything you need—player names, team affiliation, victorious state, civ ids, etc.

This data is actually what AoE sends back to the lobbying application (like Voobly) after a game is complete. That's why it's only available in multiplayer games. UserPatch just tacks it onto the end of the recorded game file as well.

There is also a C# port of RecAnalyst that may be easier to understand or reuse parts of in AoE Tools: https://github.com/louixchan/age-of-empires-analyst I've not checked it out in detail but I believe it does everything PHP RecAnalyst does and a bit more.

[BodyAnalyzer.php]: https://github.com/goto-bus-stop/recanalyst/blob/master/src/Analyzers/BodyAnalyzer.php

**Comment by goto-bus-stop** [comment]
Hmm I see. Tbh, spending many hours on getting reading of rec game files working is to be expected :smile: It took 4 or 5 months to figure out how to read HD 5.x games. Rec game files are designed to be run by the game, not to be read by third parties.

I can't tell you the correct location because it's different for every recorded game file. The game body starts at the offset specified in the int32 in the first 4 bytes of the file. The game body is a list of operations of different sizes. You have to inspect each operation to calculate the size, they're not consistent.

| Type | Content | Size |
|-|-|-|
| int32 | Operation type | 4 bytes |

 * If operation type == 3 or operation type == 4, it's followed by:

   | Type | Content | Size |
   |-|-|-|
   | int32 | Command type | 4 bytes |

   * If the command type == 0x01F4, skip 20 bytes ("start" block)
   * If the command type == -1, it's a chat message.
     
     | Type | Content | Size |
     |-|-|-|
     | int32 | Message length | 4 bytes |
     | string | Message content | (Message length) 

 * If operation type == 2, it's a sync message. Sync messages contain checksums, time elapsed since the last sync message, and the POV player's current viewport.
    * Skip 4 bytes
    * Read 4 bytes into an int32
      * if that == 0, skip 28 bytes
    * Skip 12 bytes
 * If operation type == 1, it's an action message:

   | Type | Content | Size |
   |-|-|-|
   | int32 | Action size | 4 bytes |
   | uint8 | Action type | 1 byte |
   
   The content of each action differs.
   * If action type == 0xFF, it's the post game message / achievements block mentioned before, with that structure
   * Else, skip "Action size" bytes
   * Skip another 4 bytes

That's really all I can give you. The first two links in https://github.com/goto-bus-stop/recanalyst/blob/master/references.md have similar information in different formats. Bari's overview is especially handy once you learn how to read it IMO. UserPatch didn't make any major changes besides adding the 0xFF post-game data action ("command" in Bari's terminology).

**Comment by gregstein** [comment]
wow that's crazy! Thank you very much! I couldn't ask for a better answer. I actually wasn't aware of skip bytes so i supposed I need to run a few experiments to learn more about all this.

Thank you again for this organized answer<3

**Comment by gregstein** [comment]
I just wanna ask you about the WK & 1.5RC. What is the easiest way to differentiate between the two through extracted stream in HEX? This has more priority in my project AoE2Tools so when players drag and drop replays it should automatically recognize whether it is version WK or 1.5RC. Hopefully a simple check to avoid long queries.
Thanks very much!

**Comment by goto-bus-stop** [comment]
my understanding is that WK is only differentiable via the mod identifier player resource in UP 1.5 _or_ by whether a Feitoria trickle resource is available. Getting to the player resource data is a little tricky because it's also not at a fixed offset—you have to skip the AI scripts in games that have them and skip the map data which is also variable length (obviously depends on map size). Since you primarily support UP it should only be a few fixed size skips and 2 or so variable size skips, the tricky part is figuring out how large the skips should be :)

I'm on vacation right now but I'll probably write a JS script to get to the mod identifier myself soon for my other (incomplete) rec analyzer project [recage](https://github.com/goto-bus-stop/recage), I'll post here when I have something.

**Comment by gregstein** [comment]
There should be an easier way though. apart from Feitoria is it possible an int16 or int32 differs from one version to another? I am not as knowledgeable and experience as you are, but i am hoping you could figure out an easier way.

Thank you again for this intuitive interaction! and Kudos for the js script project!! I am keeping an eye on it.
Enjoy you vacation :)

**Comment by goto-bus-stop** [comment]
Unfortunately the format is exactly the same for WK and UserPatch games. Recorded games also store unit statistics for each civilization, which would be different in WK, but they are more difficult to get to than resources and less reliable too. For one the AI information is stored at the very start of the game, so that has to be accounted for no matter what you want to read, and the map data is also very early on. Compared to most other things, finding the feitoria resource is easy! There is really no way around it because the recorded game file format is not much better than a memory dump. :(



On 5 August 2018 18:52:56 CEST, gregstein <notifications@github.com> wrote:
>There should be an easier way though. apart from Feitoria is it
>possible an int16 or int32 differs from one version to another? I am
>not as knowledgeable and experience as you are, but i am hoping you
>could figure out an easier way.
>
>Thank you again for this intuitive interaction! and Kudos for the js
>script project!! I am keeping an eye on it.
>Enjoy you vacation :)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/goto-bus-stop/recanalyst/issues/60#issuecomment-410532839

-- 
Sent from mobile. Please excuse my brevity.

**Comment by goto-bus-stop** [comment]
Finished the mod detection script here: https://github.com/goto-bus-stop/recage/blob/e824c44df80c26ff8d4252d82b38921ac10f34f7/tools/getModVersion.js

The interesting part starts at line 39. Unfortunately it's quite a bit more complex than I expected, there is a lot of variable length data in there before player resources.

It uses the JS DataView API, a similar C# class is [BinaryReader](https://msdn.microsoft.com/en-us/library/system.io.binaryreader.aspx). There is a difference though, because C#'s BinaryReader keeps track of the offset into the stream, while you have to manage it manually in JS. To illustrate the difference:
```js
const numStrings = view.getInt16(offset, true)
offset += 6
```
The C# equivalent would be:
```cs
int numStrings = reader.ReadInt16();
// Note that we're only skipping 4 bytes here instead of 6 because
// the ReadInt16() call already consumed the other 2.
reader.BaseStream.Seek(4, SeekOrigin.Current);
```

**Comment by gregstein** [comment]
You are a genius my friend! Thank you for the mod detection!! I think I can now do everything I need with your recage library. And especially thanks for the c# comments, I see now why most of my attempts reading the rec failed because of the consumption of 2 bytes which i didn't know about. 

I am excited now! Once I am back home I'm gonna try this. Thanks <3

**Comment by gregstein** [comment]
I am gonna close this issue as resolved as you have provided me with many good answers and tips. Great Dev! Great work! Love you man!
